# =========================================================
# Netlify 빌드 설정: Flutter Web 빌드 스크립트 실행
# =========================================================
[build]
  # 빌드 명령: 새로 만든 쉘 스크립트를 실행
  command = "bash ./netlify-build.sh"

  # 배포 폴더: Flutter Web 결과물 경로
  publish = "build/web" 

# =========================================================
# 라우팅 문제 해결: 모든 요청을 index.html로 리다이렉트
# =========================================================
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200