# =========================================================
# Netlify 빌드 및 배포 설정 (Flutter Web 최적화)
# =========================================================

[build]
  # 빌드 명령어: "flutter build web"으로 명확하게 지정합니다.
  command = "flutter build web"

  # 빌드 폴더: Flutter Web은 반드시 'build/web' 폴더를 배포해야 합니다.
  publish = "build/web" 

# =========================================================
# 라우팅 문제 해결 (가장 중요!)
# =========================================================
# Flutter Web 앱의 클라이언트 라우팅을 위해 모든 경로를 index.html로 서브합니다.
# 이 설정이 없으면 메인 페이지 외에는 '404 에러'가 발생합니다.

[[redirects]]
  # 모든 경로(URL)
  from = "/*"
  # index.html로 서브 (publish 경로 기준의 index.html)
  to = "/index.html"
  # 상태 코드는 200(OK)을 유지하여 정상적인 페이지처럼 보이게 합니다.
  status = 200