# =========================================================
# Netlify 빌드 설정: Flutter Web 빌드 스크립트 실행
# =========================================================
[build]
  command = "bash ./netlify-build.sh"

  # 배포 폴더: 루트 기준 build/web (Flutter Web 기본 경로)
  publish = "build/web" 

  # Node.js 플러그인 간섭을 막기 위해 환경 변수를 명시 (안정 버전)
  environment = { NODE_VERSION = "18" }

# =========================================================
# 라우팅 문제 해결
# =========================================================
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200